<h3>LIBRERIAS</h3>

In [1]:
import pandas as pd
from pathlib import Path

<h3>CARGAR</h3>

In [2]:
ruta_parquet = Path(r"../1. Datasets/1. Dataset Original")

df_dtm = pd.read_csv(ruta_parquet/"dopamine_trigger_metrics.csv")

<h3>DIAGNOSTICO Y LIMPIEZA - DOPAMINE TRIGGER METRICS</h3>

In [3]:
# ENCABEZADO
df_dtm.head()

,user_id,year,country,age_group,gender,platform,engagement_rate,short_video_consumption_hours,dopamine_trigger_score,content_refresh_frequency,instant_gratification_dependency
0,12136,2054,Spain,Teen,Male,Snapchat,78.70,3.70,62.71,48,36.53
1,3774,2039,Canada,Senior,Female,TikTok,6.40,4.09,3.67,186,32.79
2,21305,2030,USA,Children,Male,Discord,82.20,2.88,18.75,45,76.64
3,19767,2057,Japan,Young Adult,Male,YouTube,62.29,2.15,4.62,91,5.78
4,19584,2049,Turkey,Children,Other,Twitch,80.69,0.14,63.87,125,87.84

In [4]:
# ANALISIS DESCRIPTIVO
df_dtm.describe()

,user_id,year,engagement_rate,short_video_consumption_hours,dopamine_trigger_score,content_refresh_frequency,instant_gratification_dependency
count,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,12480.74506,2034.984980,50.089383,4.997003,49.965440,100.297720,49.899808
std,7237.08392,14.733202,28.855822,2.889475,28.812579,57.584251,28.748272
min,1.00000,2010.000000,0.000000,0.000000,0.000000,1.000000,0.000000
25%,6186.00000,2022.000000,25.010000,2.490000,25.117500,50.000000,25.080000
50%,12475.50000,2035.000000,50.245000,4.980000,50.080000,101.000000,49.810000
75%,18753.00000,2048.000000,75.100000,7.500000,74.850000,150.000000,74.780000
max,25000.00000,2060.000000,100.000000,10.000000,100.000000,199.000000,99.990000

In [5]:
# INFORMACIÓN
df_dtm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   user_id                           50000 non-null  int64
 1   year                              50000 non-null  int64
 2   country                           50000 non-null  object
 3   age_group                         50000 non-null  object
 4   gender                            50000 non-null  object
 5   platform                          50000 non-null  object
 6   engagement_rate                   50000 non-null  float64
 7   short_video_consumption_hours     50000 non-null  float64
 8   dopamine_trigger_score            50000 non-null  float64
 9   content_refresh_frequency         50000 non-null  int64
 10  instant_gratification_dependency  50000 non-null  float64
dtypes: float64(4), int64(3), object(4)
memory usage: 4.2+ MB

In [6]:
# VERIFICACIÓN DE NULOS
df_dtm.isnull().sum()

user_id                             0
year                                0
country                             0
age_group                           0
gender                              0
platform                            0
engagement_rate                     0
short_video_consumption_hours       0
dopamine_trigger_score              0
content_refresh_frequency           0
instant_gratification_dependency    0
dtype: int64

In [7]:
# RANGO AÑO 
print("Min:", df_dtm['year'].min(), "| Max:", df_dtm['year'].max())

Min: 2010 | Max: 2060

In [8]:
# CONVERTIR USER_ID EN STRING
df_dtm['user_id'] = df_dtm['user_id'].astype(str)

#ELIMNAR COLUMAN CONTENT_REFRESH_FRECUENCY
df_dtm.drop(columns=['content_refresh_frequency'], inplace=True)

In [9]:
# CAMBIAR NOMBRE DE COLUMNAS
df_dtm.rename(columns={
    'user_id'                          : 'id_usuario',
    'year'                             : 'anio',
    'country'                          : 'pais',
    'age_group'                        : 'grupo_edad',
    'gender'                           : 'genero',
    'platform'                         : 'plataforma',
    'engagement_rate'                  : 'tasa_interaccion',
    'short_video_consumption_hours'    : 'horas_consumo_video_corto',
    'dopamine_trigger_score'           : 'puntaje_activacion_dopamina',
    'instant_gratification_dependency' : 'dependencia_gratificacion_inmediata'
}, inplace=True)

In [10]:
# VERIFICACIÓN
df_dtm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 10 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   id_usuario                           50000 non-null  object
 1   anio                                 50000 non-null  int64
 2   pais                                 50000 non-null  object
 3   grupo_edad                           50000 non-null  object
 4   genero                               50000 non-null  object
 5   plataforma                           50000 non-null  object
 6   tasa_interaccion                     50000 non-null  float64
 7   horas_consumo_video_corto            50000 non-null  float64
 8   puntaje_activacion_dopamina          50000 non-null  float64
 9   dependencia_gratificacion_inmediata  50000 non-null  float64
dtypes: float64(4), int64(1), object(5)
memory usage: 3.8+ MB

<h3>AGREGACIÓN DE NUEVOS ATRIBUTOS</h3>

In [11]:
# CONSUMO VIDEO CATEGORIA
bins = [0, 2, 5, 8, 10]
labels = ['Bajo', 'Moderado', 'Alto', 'Severo']
df_dtm['consumo_video_categoria'] = pd.cut(df_dtm['horas_consumo_video_corto'], bins=bins, labels=labels, include_lowest=True)

#Categoriza las horas de consumo de video corto en niveles. En contexto clínico más de 5 horas diarias de video corto se considera consumo problemático.

# TASA INTERACCION CATEGORIA
bins = [0, 33, 66, 100]
labels = ['Baja', 'Media', 'Alta']
df_dtm['tasa_interaccion_categoria'] = pd.cut(df_dtm['tasa_interaccion'], bins=bins, labels=labels, include_lowest=True)

#Agrupa la tasa de interacción en tercios.

In [ ]:
# RUTA DONDE SE GUARDARÁN LOS PARQUET
ruta_limpio = Path(r"../1. Datasets/3. Dataset Limpio-csv")

# EXPORTAR CADA DATASET COMO PARQUET
df_dtm.to_parquet(ruta_limpio/"dopamine_trigger_metrics.parquet", index=False)

# EXPORTAR CADA DATASET COMO CSV
df_dtm.to_csv(ruta_limpio/"dopamine_trigger_metrics.csv", index=False)