<h3>LIBRERIAS</h3>

In [ ]:
import pandas as pd
from pathlib import Path

<h3>CARGAR</h3>

In [ ]:
ruta_parquet = Path(r"../1. Datasets/1. Dataset Original")

df_sd = pd.read_csv(ruta_parquet/"sleep_disruption.csv")

<h3>DIAGNOSTICO Y LIMPIEZA - SLEEP DISRUPTION</h3>

In [ ]:
# ENCABEZADO
df_sd.head()

,user_id,year,country,age_group,gender,platform,avg_sleep_hours,sleep_quality_score,late_night_usage_hours,night_notifications,fatigue_level
0,16429,2060,Canada,Young Adult,Male,Twitch,6.65,82.07,4.43,33,27.18
1,8126,2041,Saudi Arabia,Senior,Male,Facebook,4.86,58.04,5.30,42,80.17
2,3247,2023,Japan,Teen,Male,Snapchat,6.04,67.19,2.69,37,4.87
3,15986,2040,Italy,Senior,Female,X/Twitter,6.87,64.08,1.44,27,10.65
4,2914,2057,South Korea,Teen,Male,YouTube,6.16,61.54,1.26,59,1.83

In [ ]:
# ANALISIS DESCRIPTIVO
df_sd.describe()

,user_id,year,avg_sleep_hours,sleep_quality_score,late_night_usage_hours,night_notifications,fatigue_level
count,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000
mean,12492.148040,2034.945760,6.500073,57.90966,2.991941,29.455320,50.104836
std,7221.600961,14.733311,1.499513,17.76031,1.728440,17.266425,28.828481
min,1.000000,2010.000000,2.000000,0.00000,0.000000,0.000000,0.000000
25%,6248.000000,2022.000000,5.490000,45.90000,1.500000,15.000000,25.330000
50%,12458.000000,2035.000000,6.500000,57.93000,3.000000,29.000000,50.030000
75%,18732.000000,2048.000000,7.510000,70.12000,4.490000,44.000000,75.190000
max,25000.000000,2060.000000,12.000000,100.00000,6.000000,59.000000,100.000000

In [ ]:
# INFORMACIÓN
df_sd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   user_id                 50000 non-null  int64
 1   year                    50000 non-null  int64
 2   country                 50000 non-null  object
 3   age_group               50000 non-null  object
 4   gender                  50000 non-null  object
 5   platform                50000 non-null  object
 6   avg_sleep_hours         50000 non-null  float64
 7   sleep_quality_score     50000 non-null  float64
 8   late_night_usage_hours  50000 non-null  float64
 9   night_notifications     50000 non-null  int64
 10  fatigue_level           50000 non-null  float64
dtypes: float64(4), int64(3), object(4)
memory usage: 4.2+ MB

In [ ]:
# VERIFICACIÓN DE NULOS
df_sd.isnull().sum()

user_id                   0
year                      0
country                   0
age_group                 0
gender                    0
platform                  0
avg_sleep_hours           0
sleep_quality_score       0
late_night_usage_hours    0
night_notifications       0
fatigue_level             0
dtype: int64

In [ ]:
# RANGO AÑO 
print("Min:", df_sd['year'].min(), "| Max:", df_sd['year'].max())

Min: 2010 | Max: 2060

In [ ]:
# CONVERTIR USER_ID EN STRING
df_sd['user_id'] = df_sd['user_id'].astype(str)

# ELIMNAR COLUMNA NIGTH_NOTIFICATIONS
df_sd.drop(columns=['night_notifications'], inplace=True)

In [ ]:
# CAMBIAR NOMBRE DE COLUMNAS
df_sd.rename(columns={
    'user_id'               : 'id_usuario',
    'year'                  : 'anio',
    'country'               : 'pais',
    'age_group'             : 'grupo_edad',
    'gender'                : 'genero',
    'platform'              : 'plataforma',
    'avg_sleep_hours'       : 'promedio_horas_sueno',
    'sleep_quality_score'   : 'puntaje_calidad_sueno',
    'late_night_usage_hours': 'horas_uso_nocturno',
    'fatigue_level'         : 'nivel_fatiga'
}, inplace=True)

In [ ]:
# VERIFICACIÓN
df_sd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id_usuario             50000 non-null  object
 1   anio                   50000 non-null  int64
 2   pais                   50000 non-null  object
 3   grupo_edad             50000 non-null  object
 4   genero                 50000 non-null  object
 5   plataforma             50000 non-null  object
 6   promedio_horas_sueno   50000 non-null  float64
 7   puntaje_calidad_sueno  50000 non-null  float64
 8   horas_uso_nocturno     50000 non-null  float64
 9   nivel_fatiga           50000 non-null  float64
dtypes: float64(4), int64(1), object(5)
memory usage: 3.8+ MB

<h3>AGREGACIÓN DE NUEVOS ATRIBUTOS</h3>

In [ ]:
# CLASIFICADOR DE SUEÑO
bins = [0, 5, 7, 9, 12]
labels = ['Insuficiente', 'Aceptable', 'Optimo', 'Excesivo']
df_sd['clasificacion_sueno'] = pd.cut(df_sd['promedio_horas_sueno'], bins=bins, labels=labels, include_lowest=True)

# Categoriza las horas de sueño según los estándares clínicos de la National Sleep Foundation: menos de 5 horas es insuficiente, 7–9 es el rango óptimo. 
# Útil para identificar pacientes en riesgo por privación de sueño.

#FATIGA CATEGORIA
bins = [0, 33, 66, 100]
labels = ['Leve', 'Moderada', 'Severa']
df_sd['fatiga_categoria'] = pd.cut(df_sd['nivel_fatiga'], bins=bins, labels=labels, include_lowest=True)

In [ ]:
df_sd

,id_usuario,anio,pais,grupo_edad,genero,plataforma,promedio_horas_sueno,puntaje_calidad_sueno,horas_uso_nocturno,nivel_fatiga,clasificacion_sueno,fatiga_categoria
0,16429,2060,Canada,Young Adult,Male,Twitch,6.65,82.07,4.43,27.18,Aceptable,Leve
1,8126,2041,Saudi Arabia,Senior,Male,Facebook,4.86,58.04,5.30,80.17,Insuficiente,Severa
2,3247,2023,Japan,Teen,Male,Snapchat,6.04,67.19,2.69,4.87,Aceptable,Leve
3,15986,2040,Italy,Senior,Female,X/Twitter,6.87,64.08,1.44,10.65,Aceptable,Leve
4,2914,2057,South Korea,Teen,Male,YouTube,6.16,61.54,1.26,1.83,Aceptable,Leve
...,...,...,...,...,...,...,...,...,...,...,...,...
49995,22763,2034,Pakistan,Young Adult,Other,Facebook,5.54,83.84,3.50,80.14,Aceptable,Severa
49996,23658,2024,Germany,Teen,Other,LinkedIn,7.11,71.28,1.66,38.84,Optimo,Moderada
49997,13660,2025,Australia,Senior,Female,TikTok,6.45,49.97,2.56,19.45,Aceptable,Leve
49998,14089,2015,Saudi Arabia,Teen,Other,Instagram,7.48,54.52,3.94,99.57,Optimo,Severa
49999,24190,2015,Saudi Arabia,Teen,Other,Reddit,7.49,73.84,4.61,28.16,Optimo,Leve

In [ ]:
# RUTA DONDE SE GUARDARÁN LOS PARQUET
ruta_limpio = Path(r"../1. Datasets/2. Dataset Limpio")

# EXPORTAR CADA DATASET COMO PARQUET
#df_sd.to_parquet(ruta_limpio/"sleep_disruption.parquet", index=False)

# EXPORTAR CADA DATASET COMO CSV
df_sd.to_csv(ruta_limpio/"sleep_disruption.csv", index=False)